description = "Remove beta flag from all languages to make them selectable on mobile"
authors = ["SBence"]
supported_platforms = ["android", "ios"]

[[patch_lists]]
  version = 0
  supported_game_versions = ["1.0.1f-FULL", "1.0.1e-FULL", "1.0.0n-FULL"]
  [[patch_lists.patch_files]]
    target_file = "game.lua"
    [[patch_lists.patch_files.patches]]
      search_string = "['id'] = {font = 1, label = \"Bahasa Indonesia\", key = 'id', beta = true, button = \"Umpan Balik Bahasa\", warning = {'Bahasa ini masih dalam tahap Beta. Untuk membantu','kami meningkatkannya, silakan klik tombol umpan balik.', \"Klik lagi untuk mengonfirmasi\"}}"
      patch_content = """
            ['id'] = {font = 1, label = \"Bahasa Indonesia\", key = 'id', beta = nil, button = \"Umpan Balik Bahasa\", warning = {'Bahasa ini masih dalam tahap Beta. Untuk membantu','kami meningkatkannya, silakan klik tombol umpan balik.', \"Klik lagi untuk mengonfirmasi\"}},
"""

  [[patch_lists.patch_files]]
    target_file = "game.lua"
    [[patch_lists.patch_files.patches]]
      search_string = "['ko'] = {font = 4, label = \"한국어\", key = 'ko', beta = true, button = \"번역 피드백\", warning = {'이 언어는 아직 베타 단계에 있습니다. ','번역을 도와주시려면 피드백 버튼을 눌러주세요.', \"다시 클릭해서 확인하세요\"}}"
      patch_content = """
            ['ko'] = {font = 4, label = \"한국어\", key = 'ko', beta = nil, button = \"번역 피드백\", warning = {'이 언어는 아직 베타 단계에 있습니다. ','번역을 도와주시려면 피드백 버튼을 눌러주세요.', \"다시 클릭해서 확인하세요\"}},
"""

  [[patch_lists.patch_files]]
    target_file = "game.lua"
    [[patch_lists.patch_files.patches]]
      search_string = "['ru'] = {font = 6, label = \"Русский\", key = 'ru', beta = true, button = \"Отзыв о языке\", warning = {'Этот язык все еще находится в Бета-версии. Чтобы помочь','нам его улучшить, пожалуйста, нажмите на кнопку обратной связи.', \"Щелкните снова, чтобы подтвердить\"}}"
      patch_content = """
            ['ru'] = {font = 6, label = \"Русский\", key = 'ru', beta = nil, button = \"Отзыв о языке\", warning = {'Этот язык все еще находится в Бета-версии. Чтобы помочь','нам его улучшить, пожалуйста, нажмите на кнопку обратной связи.', \"Щелкните снова, чтобы подтвердить\"}},
"""